import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  <header className="bg-gray-800 text-white p-4">
      <nav className="container mx-auto flex justify-between">
      <Link href="/" className="text-xl">My Brand</Link>
            <div>
              <Link href="/services" className="mx-2">Services</Link>
              <Link href="/about" className="mx-2">About</Link>
              <Link href="/contact" className="mx-2">Contact Us</Link>
            </div>
      </nav>
    </header>
    <main className="container mx-auto p-4">{children}</main>
    <footer className="bg-gray-800 text-white p-4 text-center">
      © {new Date().getFullYear()} My Brand
    </footer>
      </body>
    </html>
  );
}
